### ISSUE TITLE
Add support for Angular Libraries

### ISSUE THREAD

**Issue by Kamieniu** [ngneat/tailwind#12]
**Is your feature request related to a problem? Please describe.**
There is no support to Build Angular Library using TailwindCSS.

**Describe the solution you'd like**
Probably some custom ng-packagr builder that would compile Angular code along with TailwindCSS

**Comment by cgatian** [comment]
@Kamieniu I looked into this per [this issue](https://github.com/ng-packagr/ng-packagr/issues/1471#issuecomment-707327200) and added details why it's currently not possible.

I started building out a custom build pipeline that could compile tailwind alongside the component styles. I think it will work nicely because if you adopt tailwind you are also reducing the amount of CSS required for each component, because all styling _should_ be class driven within the template. For the areas where usage of `theme()` or `apply()` is desired on the component I utilize a component.tailwind.css file to be created alongside the component. This gets picked up and compiled into a `theme.css` file in the dist. This is similar to what [scss-bundle](https://github.com/reactway/scss-bundle) does.

**Comment by cgatian** [comment]
Here's a diagram outlining this process
![Tailwind Build process](https://user-images.githubusercontent.com/1752170/96295178-77508a00-0fbb-11eb-901e-4bb510f2c966.png)

**Comment by cgatian** [comment]
If I could kindly ask, why was this closed?

**Comment by nartc** [comment]
@cgatian because this request is outside the scope of this schematics. ngneat/tailwind deals with setting up your project with Tailwind so you don't have to set one up manually with custom webpack. Whatever else you do with the config to support specifically what you need is not supported.

With that said, I understand this is an interesting request and needed. If you could provide a more complete Feature Request outlinging what solution you've thought of, any alternatives? Then we can discuss. I can't guarantee it's possible or I'm able to make it happen though. 

You want to reopen this issue? Or open a new one with more info?
