### ISSUE TITLE
Enhancement: only install 'postcss-ng-tailwind-in-components' if darkMode is selected

### ISSUE THREAD

**Issue by nartc** [ngneat/tailwind#66]
cc @vltansky 

What do you think? Is it worth it?

**Comment by vltansky** [comment]
I think it should be included always, especially as its about 2kb, as you can start using dark mode, not today (when performing adding tailwind), but in one month and you won't understand why it's not working, you won't think about rerunning schematics again. Maybe instead of adding it to clients dependency - better to declare it as ngneat/tailwind dependency

**Comment by nartc** [comment]
Makes sense!
