### ISSUE TITLE
The CLI not working with Angular 8

### ISSUE THREAD

**Issue by davidrock** [ngneat/tailwind#84]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I am running the cli tool with `ng add @ngneat/tailwind`, it stuck in "What @tailwindcss plugins do you want to enable?", I can't pass through it. No plugin options are shown and I tried to write there but it doesn't accept anything. The only way to get out is using Ctrl+C.

It seemed to be working fine in a newer version of angular.

## Expected behavior

The same flow as the GIF image show in the README, it should show some plugins options for me to select.

## Minimal reproduction of the problem with instructions

```zsh
ng add @ngneat/tailwind
? Would you like to enable dark mode? class
? Would you like to use tailwind directives & functions in component styles? (might increase build time) Yes
? What @tailwindcss plugins do you want to enable? 
```

<pre><code>
Angular version: 8.2.13

For Tooling issues:
- Node version: 14.16.0 (I tried with version 12 too but got the same results)
- Platform:  Mac

**Comment by vltansky** [comment]
https://github.com/ngneat/tailwind#versions

did you try version v5.2.5?

**Comment by davidrock** [comment]
> https://github.com/ngneat/tailwind#versions
> 
> did you try version v5.2.5?

Yes, I did try to run like this: `ng add @ngneat/tailwind@5`

**Comment by nartc** [comment]
@davidrock Sorry for the late response. There is a workaround for old projects

```
ng add @ngneat/tailwind@5.2.5 --plugins=forms
```

`plugins` is a `oneOf` and probably didn't get supported in old versions of AngularCLI. Hence, we workaround by providing it via the command. I'm picking `forms` since it's the easiest to remember. You can, after the fact, uninstall it and remove it from `tailwind.config.js`

You'd also need to downgrade `@angular-builders/custom-webpack` by running `npm install @angular-builders/custom-webpack@8`. Then everything should work. If there's an error saying `Cannot find @ngneat/tailwind`, go ahead and install it as a devDependency with `npm i -DE @ngneat/tailwind@5.2.5`

Hope this helps clarifying some stuffs :)
